In [150]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as stat

In [151]:
Crop = pd.read_csv('./cropdata.csv')
Crop = Crop.sort_values('label')


In [152]:
Crop = Crop.reset_index()
Crop

index    N    P    K  temperature   humidity        ph    rainfall  \
0      1524   29  144  204    22.433245  92.486677  5.800449  119.102519   
1      1526   13  144  197    22.921571  94.896134  6.280223  105.694154   
2      1527   25  143  198    22.812125  91.518617  6.027314  107.855225   
3      1528    9  137  200    21.121521  90.687877  5.636687  102.801720   
4      1529    6  144  198    21.114787  90.315287  5.559364  104.508662   
...     ...  ...  ...  ...          ...        ...       ...         ...   
2195   1370   97   22   50    26.260287  86.145859  6.769894   58.978788   
2196   1371  117   30   50    24.901239  87.207729  6.744966   46.592073   
2197   1372   90   14   52    24.847408  89.204546  6.391858   59.679272   
2198   1362  111    6   53    26.493065  88.591431  6.313513   46.063822   
2199   1399  120   24   47    26.986037  89.413849  6.260839   58.548767   

           label  
0          apple  
1          apple  
2          apple  
3          apple  
4          apple  
...          ...  
2195  watermelon  
2196  watermelon  
2197  watermelon  
2198  watermelon  
2199  watermelon  

[2200 rows x 9 columns]

In [153]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = Crop['label'].to_numpy()
values = array(data)
print(values)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[1502, :])])
print(inverted)

['apple' 'apple' 'apple' ... 'watermelon' 'watermelon' 'watermelon']
[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['apple']


In [154]:
names = Crop['label'].unique()

In [156]:
newLabel = pd.DataFrame(onehot_encoded)

newLabel.columns = [names]


In [171]:
newLabel.shape

(2200, 22)

In [158]:
Crop = Crop.drop(['label'], axis =1)

In [144]:
#df2 = pd.concat([Crop, newLabel], axis = 1)

In [145]:
#Crop = Crop.join(newLabel)

In [159]:
Crop

index    N    P    K  temperature   humidity        ph    rainfall
0      1524   29  144  204    22.433245  92.486677  5.800449  119.102519
1      1526   13  144  197    22.921571  94.896134  6.280223  105.694154
2      1527   25  143  198    22.812125  91.518617  6.027314  107.855225
3      1528    9  137  200    21.121521  90.687877  5.636687  102.801720
4      1529    6  144  198    21.114787  90.315287  5.559364  104.508662
...     ...  ...  ...  ...          ...        ...       ...         ...
2195   1370   97   22   50    26.260287  86.145859  6.769894   58.978788
2196   1371  117   30   50    24.901239  87.207729  6.744966   46.592073
2197   1372   90   14   52    24.847408  89.204546  6.391858   59.679272
2198   1362  111    6   53    26.493065  88.591431  6.313513   46.063822
2199   1399  120   24   47    26.986037  89.413849  6.260839   58.548767

[2200 rows x 8 columns]

In [160]:
X=Crop
y=newLabel

In [164]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,
                                               shuffle=True,random_state=0)

In [165]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [188]:
model = keras.Sequential(
    [
        layers.Dense(8, activation="relu"),
        layers.Dense(32, activation="relu"),
        layers.Dense(32, activation="relu"),
        layers.Dense(32),
        layers.Dense(22, activation="sigmoid"),
    ]
)

In [189]:
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])

In [190]:
model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=2)

Epoch 1/150
55/55 - 1s - loss: 0.2454 - accuracy: 0.0568
Epoch 2/150
55/55 - 0s - loss: 0.1130 - accuracy: 0.1131
Epoch 3/150
55/55 - 0s - loss: 0.0415 - accuracy: 0.0972
Epoch 4/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.0966
Epoch 5/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.0977
Epoch 6/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1080
Epoch 7/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1023
Epoch 8/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1051
Epoch 9/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1091
Epoch 10/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1119
Epoch 11/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1136
Epoch 12/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1108
Epoch 13/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1187
Epoch 14/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1216
Epoch 15/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1187
Epoch 16/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1216
Epoch 17/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1227
Epoch 18/150
55/55 - 0s

Epoch 142/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1324
Epoch 143/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1324
Epoch 144/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1324
Epoch 145/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1324
Epoch 146/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1324
Epoch 147/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1324
Epoch 148/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1324
Epoch 149/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1324
Epoch 150/150
55/55 - 0s - loss: 0.0414 - accuracy: 0.1324


In [192]:
predictions = model.predict(X_test)

In [194]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predictions)

In [196]:
print(mae)

0.041121813359312843


In [203]:
print(np.max(predictions[0]))

1.0180501e-11


In [9]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf=RandomForestClassifier(n_estimators=10,criterion="entropy")
classifier_rf.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [10]:
y_pred=classifier_rf.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred, y_test)
print('Random Forest Model accuracy score: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

Random Forest Model accuracy score: 0.9890
